- name: variables
  hosts: localhost
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120HRS 
    TRAINER: Siva
  tasks:
  - name: print the variable
    debug:
      msg: "course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"
