- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"