- name: variables
  hosts: localhost
  connection: local
  vars: #PLAY LEVEL VARIABLES
    GREET: "FROM PLAY"
  #vars_files:
    #- vars.yaml
  #vars_prompt:
    #- name: GREET
      #prompt: Enter the value
      #private: false

  tasks:
  - name: print the variable
    #vars: #TASK LEVEL VARIABLES
      #GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

