- name: Install package using loops concept
  hosts: web
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{name.item}}"
      state: "{{state.item}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'gcc', state: 'present'}
    - {name: 'zip', state: 'absent'}
