- name: Filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello {{person | default('Ramesh')}}"
      msg: "Hello {{number | default(100)}}"